---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Causal Modelling in Education

``` {r}
library(tidyverse)
library(bnlearn)
library(dagitty)

```

## Exploring `dataedu` open data package

``` {r processing-data}
library(dataedu)

# Pre-survey for the F15 and S16 semesters
pre_survey <- dataedu::pre_survey

# Gradebook and log-trace data for F15 and S16 semesters
course_data <- dataedu::course_data

# Log-trace data for F15 and S16 semesters - this is for time spent
course_minutes <- dataedu::course_minutes

pre_survey  <-
  pre_survey  %>%
  # Rename the qustions something easier to work with because R is case sensitive
  # and working with variable names in mix case is prone to error
  rename(
    q1 = Q1MaincellgroupRow1,
    q2 = Q1MaincellgroupRow2,
    q3 = Q1MaincellgroupRow3,
    q4 = Q1MaincellgroupRow4,
    q5 = Q1MaincellgroupRow5,
    q6 = Q1MaincellgroupRow6,
    q7 = Q1MaincellgroupRow7,
    q8 = Q1MaincellgroupRow8,
    q9 = Q1MaincellgroupRow9,
    q10 = Q1MaincellgroupRow10
  ) %>%
  # Convert all question responses to numeric
  mutate_at(vars(q1:q10), list( ~ as.numeric(.)))

pre_survey <-
  pre_survey %>%
  mutate(q4 = 6 - q4,
         q7 = 6 - q7)

pre_survey <-
  pre_survey %>%
  rename(student_id = opdata_username,
         course_id = opdata_CourseID)

# Re-create the variable "student_id" so that it excludes the extraneous characters
pre_survey <- pre_survey %>% 
  mutate(student_id = str_sub(student_id, start = 2, end = -3))

# Save the new variable as numeric so that R no longer thinks it is text 
pre_survey <- pre_survey %>% 
  mutate(student_id = as.numeric(student_id))

measure_mean_by_student <-
  pre_survey %>%
  # Gather questions and responses
  pivot_longer(cols = q1:q10,
               names_to = "question",
               values_to = "response") %>% 
  mutate(
    measure = case_when(
      question %in% c("q1", "q4", "q5", "q8", "q10") ~ "int",
      question %in% c("q2", "q6", "q9") ~ "uv",
      question %in% c("q3", "q7") ~ "pc",
      TRUE ~ NA_character_)) %>%
  group_by(student_id, course_id, measure) %>%
  summarize(
    mean_response = mean(response, na.rm = TRUE)) %>% 
  pivot_wider(
    id_cols = student_id:course_id,
    names_from = measure,
    values_from = mean_response
  )


# split course section into components
course_data <- 
  course_data %>%
  # Give course subject, semester, and section their own columns
  separate(
    col = CourseSectionOrigID,
    into = c("subject", "semester", "section"),
    sep = "-",
    remove = FALSE
  )


course_data <-
  course_data %>%
  rename(student_id = Bb_UserPK,
         course_id = CourseSectionOrigID)

dat <-
  left_join(course_data, measure_mean_by_student,
            by = c("student_id", "course_id"))

course_minutes <-
  course_minutes %>%
  rename(student_id = Bb_UserPK,
         course_id = CourseSectionOrigID)

course_minutes <-
  course_minutes %>%
  # Change the data type for student_id in course_minutes so we can match to 
  # student_id in dat
  mutate(student_id = as.integer(student_id))

dat <- 
  dat %>% 
  left_join(course_minutes, 
            by = c("student_id", "course_id"))

dat_reg <- 
  dat %>% 
  select(course_id, student_id, semester, grade = FinalGradeCEMS,
         int, pc, uv, time_spent = TimeSpent) %>% 
  distinct()
# Key outcome is Final
```

``` {r}

# TODO: compare this with xg-boost or some other 'best practice' 

pairs(dat_reg %>% select(grade, int, pc, uv, time_spent))

library(bnlearn)

black_list  <-  
  tribble(
    ~from, ~to,
    "grade", "int",
    "grade", "pc",
    "grade", "uv",
    "grade", "time_spent",
    "time_spent", "int",
    "time_spent", "pc",
    "time_spent", "uv"
  )  %>% as.data.frame()

black_list %>% 
  knitr::kable(caption = "Black listed edges")

black_list_comb  <-  
  tribble(
    ~from, ~to,
    "grade", "pre_int",
    "grade", "time_spent",
    "time_spent", "pre_int",
  )  %>% as.data.frame()

black_list_comb %>% 
  knitr::kable(caption = "Black listed edges - combined model")
  
dat_cd <- dat_reg %>% 
  select(grade, int, pc, uv, time_spent) %>% 
  filter(complete.cases(.))

dat_cd_comb <- dat_cd %>% 
  mutate(pre_int = uv + pc + int) %>% 
  select(-uv, -pc, -int)

tabu.dag <- tabu(dat_cd, blacklist = black_list)

plot(tabu.dag)

hc.dag <- hc(dat_cd, blacklist = black_list)

plot(hc.dag)

pc.dag <- pc.stable(dat_cd, blacklist = black_list)

plot(pc.dag)


# This one most interesting
pc.comb.dag <- pc.stable(dat_cd_comb, blacklist = black_list_comb)

plot(pc.comb.dag)


tabu.comb.dag <- tabu(dat_cd_comb, blacklist = black_list_comb)

plot(tabu.comb.dag)

```

So it looks like time spent has a *causal* influence on grade, and pre interest *might* have an effect on grade but it is weaker, and not mediated through time spent. 

``` {r}
dat.dag <- pc.stable(dat_cd_comb, blacklist = black_list_comb)
dat.bn.fit <- bn.fit(dat.dag, data = dat_cd_comb)

bn.fit.histogram(dat.bn.fit)

```


## ChemTutor data set

``` {r}
dat_chm <- read_csv(file.path('data-raw', 'chem375_testData.csv')) %>% 
  janitor::clean_names() %>% 
  rename(
    id = anon_student_id,
    ps_error_rate = total1st_attempt_error_rate)

dat_chm_bn <- dat_chm %>% 
  select(-id) %>% 
  filter(complete.cases(.)) %>% 
  mutate(condition = factor(condition))

dat_chm_bn_gains <- dat_chm_bn %>% 
  mutate(immediate_gain = immediate_posttest - pretest,
         delayed_gain = delayed_posttest - pretest) %>% 
  select(-pretest, -immediate_posttest, -delayed_posttest)

black_list_chm_gains <- tribble(
  ~from, ~to,
    "spatial_skills", "condition",
    "immediate_gain", "condition",
    "delayed_gain", "condition",
    "ps_error_rate", "condition"
)

black_list_chm  <-  
  tribble(
    ~from, ~to,
    "spatial_skills", "condition",
    "pretest", "condition",
    "immediate_posttest", "condition",
    "delayed_posttest", "condition",
    "ps_error_rate", "condition",
    "condition", "pretest"
  ) %>% as.data.frame()

pc.chm.dag <- pc.stable(dat_chm_bn, blacklist = black_list_chm)
tabu.chm.dag <- tabu(dat_chm_bn, blacklist = black_list_chm)

plot(tabu.chm.dag)

tabu.chm.gain.dag <- tabu(dat_chm_bn_gains),
                          blacklist = black_list_chm_gains)

plot(tabu.chm.gain.dag)
```

